server:
  port: 9001

spring:
  application:
    name: order-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/wedding_order?serverTimezone=CTT&useSSL=false&useUnicode=true&characterEncoding=UTF-8&allowPublicKeyRetrieval=true
    username: root
    password: admin


  jpa:
    database: mysql
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
  thymeleaf:
    cache: false

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://server8771:8771/eureka/,http://server8772:8772/eureka/,http://server8773:8773/eureka/
  instance:
    instance-id: order
    prefer-ip-address: true


#  info.app.name=amber-cloud-dept-8001
#  info.company.name=www.amber.com
#  info.build.artifactId=$project.artifactId$
#  info.build.version=$project.version$
info:
  app:
    name: mainUI
  company:
    name: http://member/member/mainUI
  build:
    artfactId: ${project.artifactId}
    version: ${project.version}

